// <auto-generated />
using System;
using Fitness.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240611012157_addCompanyTable")]
    partial class addCompanyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Fitness.Models.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryDietId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDietId");

                    b.ToTable("Diet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDietId = 1,
                            Description = "Dieta niskowęglowodanowa, wysokotłuszczowa, zaprojektowana dla osób chcących zredukować wagę. Bogata w awokado, olej kokosowy, masło i orzechy.",
                            DietName = "Keto Lean 1500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/grillowany-filet-z-lososia-i-salata-ze-swiezych-warzyw-z-zielonej-salaty-i-pomidorow-z-awokado-guacamole-koncepcja-zrownowazonego-odzywiania-dla-czystego-zywienia-flexitarian-srodziemnomorskiej-diety_1150-44857.jpg?t=st=1716506783~exp=1716510383~hmac=bffdc6feec3e49acd7328b5bd83e56ea2e4c1beecf0c94b380168690acaa3744&w=1060",
                            Kcal = 1500,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryDietId = 1,
                            Description = "Utrzymanie równowagi energetycznej przy umiarkowanym spożyciu kalorii, z tłustymi rybami, mięsem karmionym trawą i zdrowymi olejami.",
                            DietName = "Keto Balance 2000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/apetyczna-salatka-ze-swiezymi-warzywami-i-jajkami-na-talerzu-w-kobiecych-rekach_169016-19087.jpg?t=st=1716509274~exp=1716512874~hmac=1b6849e25e6a0965d5e768b72343936894285f10bf779dd5a888ac4023b9422c&w=1060",
                            Kcal = 2000,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryDietId = 1,
                            Description = "Idealna dla aktywnych osób potrzebujących więcej energii. Zawiera więcej tłustych mięs, serów i oliwy z oliwek, aby dostarczyć odpowiednią ilość kalorii.",
                            DietName = "Keto Power 2500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/stek-z-kurczaka-na-czarnym-talerzu_1150-23143.jpg?t=st=1716509251~exp=1716512851~hmac=3098bd347cc4fe1e2d7dab709b2a0ddc07d6a0342180354363ae8c91a21128f5&w=1060",
                            Kcal = 2500,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryDietId = 1,
                            Description = "Maksymalna energia z tłuszczów dla osób o wysokim zapotrzebowaniu kalorycznym. Zawiera smalec, masło klarowane, tłuste ryby i duże ilości orzechów.",
                            DietName = "Keto Max 3000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/salatka-dietetyczna-z-malzami-jajkami-przepiorczymi-ogorkami-rzodkiewka-i-salata-zdrowe-jedzenie-salatka-z-owocow-morza-widok-z-gory-lezal-plasko_2829-4457.jpg?t=st=1716506871~exp=1716510471~hmac=c4655169083ef742fd9be13e6453dad686f3a266f84be782b6f0a5717b1e8d28&w=1060",
                            Kcal = 3000,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryDietId = 2,
                            Description = "Dieta skoncentrowana na chudym mięsie, rybach, jajkach i białkach roślinnych, dostarczająca białko przy minimalnej ilości tłuszczów i węglowodanów.",
                            DietName = "Protein Punch 1500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/widok-z-gory-sproszkowana-maka-na-talerzu-miski-z-maka-i-migdalami-orzechowe-jajka-przepiorcze-owies-na-stole_140725-145220.jpg?t=st=1716509316~exp=1716512916~hmac=fa8dcb351d7acfdb81cc061310e7e17efd62c70bb94e2f81eef1ee719442f2f4&w=1060",
                            Kcal = 1500,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryDietId = 2,
                            Description = "Zwiększona ilość białek z mięsa, ryb, nabiału i roślin strączkowych, z większym dodatkiem zdrowych tłuszczów i węglowodanów złożonych.",
                            DietName = "Protein Boost 2000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/zbieranie-powszechnych-alergenow-pokarmowych-dla-ludzi_23-2149870522.jpg?t=st=1716509332~exp=1716512932~hmac=6f7b0532e20884dc386eba6e3cdc202a937b760a86aa50bbf2ac568358c20c9b&w=1060",
                            Kcal = 2000,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryDietId = 2,
                            Description = "Dieta dla osób o wyższym zapotrzebowaniu energetycznym, bogata w białko z różnych źródeł oraz zdrowe tłuszcze i węglowodany.",
                            DietName = "Protein Powerhouse 2500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/zdrowe-skladniki-zywnosci-na-rustykalnym-stole_144627-30549.jpg?t=st=1716509347~exp=1716512947~hmac=f1642ccf870bf8785c0b7c9d556cf4ba9374d020b504b06a94b539f4f8230831&w=996",
                            Kcal = 2500,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryDietId = 2,
                            Description = "Maksymalna ilość białka dla sportowców i aktywnych osób, z dużą ilością mięsa, ryb, nabiału i roślin strączkowych, wspierająca regenerację i budowę mięśni.",
                            DietName = "rotein Titan 3000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/zasierzutny-widok-chlebowi-piekarnia-skladniki-z-toczna-szpilka-na-drewnianym-tle_23-2147872582.jpg?t=st=1716509372~exp=1716512972~hmac=93104a09d00383b8fc01e2b11245fb79dac747d8db00e8b1372d6ca883aa292e&w=1060",
                            Kcal = 3000,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryDietId = 3,
                            Description = "Niskokaloryczna dieta wegańska, bogata w warzywa, owoce, rośliny strączkowe i pełnoziarniste produkty, zapewniająca wszystkie niezbędne składniki odżywcze.",
                            DietName = "Green Energy 1500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/widok-z-gory-smaczne-jedzenie-dla-smakoszy-z-dipem_23-2148375712.jpg?t=st=1716509449~exp=1716513049~hmac=01bd8d5e178930b1290b23636d579f451b1d90f55cd596016f3543b6c7d23f03&w=1060",
                            Kcal = 1500,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryDietId = 3,
                            Description = "Zbilansowana dieta roślinna z większą ilością kalorii, zawierająca orzechy, nasiona, tofu i rośliny strączkowe, zapewniająca energię i zdrowie.",
                            DietName = "Vegan Vitality 2000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/swieza-salatka-z-awokado-w-rustykalnej-misce-wygenerowana-przez-ai_24640-80838.jpg?t=st=1716509434~exp=1716513034~hmac=3e48b4c465783967b0be43e8c265b5b04d0014d95b01f46c502bce877b000e02&w=1380",
                            Kcal = 2000,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryDietId = 3,
                            Description = "Dieta wegańska dla aktywnych osób, z dużą ilością roślin strączkowych, pełnoziarnistych produktów, orzechów i nasion, dostarczająca odpowiednią ilość białka i kalorii.",
                            DietName = "Plant Power 2500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/bardzo-swieza-miska-z-ziol-quinoa_53876-126673.jpg?t=st=1716509421~exp=1716513021~hmac=0df611545ce6b4a6b047d43a6cdf1ffd85955ec3fb1d2479cb1bc7219935dd53&w=996",
                            Kcal = 2500,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryDietId = 3,
                            Description = "Maksymalna energia z roślin dla osób o wysokim zapotrzebowaniu kalorycznym, z dużą ilością owoców, warzyw, roślin strączkowych, orzechów i nasion.",
                            DietName = "Vegan Fuel 3000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/zdrowa-wegetarianska-salatka-z-komosy-ryzowej-ze-swiezymi-warzywami-wygenerowana-przez-ai_24640-80498.jpg?t=st=1716509404~exp=1716513004~hmac=e61104c82a880756601d8cd9620d1a409d4952856e0e77f1f3d901fe9f4c8a9b&w=1380",
                            Kcal = 3000,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryDietId = 4,
                            Description = "Niskokaloryczna dieta wegetariańska, bogata w warzywa, owoce, nabiał i rośliny strączkowe, zapewniająca zrównoważone spożycie składników odżywczych.",
                            DietName = "Veggie Delight 1500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/odgornego-widoku-karmowy-przygotowania-na-drewnianym-tle_23-2148287541.jpg?t=st=1716509474~exp=1716513074~hmac=959b8a80f6142952c015fcc1cc6de461db4186b7565d893f5288552ff5a2675c&w=1060",
                            Kcal = 1500,
                            Price = 35.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryDietId = 4,
                            Description = "Zbilansowana dieta wegetariańska z większą ilością kalorii, zawierająca nabiał, jaja, warzywa i pełnoziarniste produkty, wspierająca zdrowie i energię.",
                            DietName = "Vegetarian Harmony 2000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/wegetarianska-miska-buddy-z-salatka-ze-swiezych-warzyw-i-ciecierzyca_1150-42361.jpg?t=st=1716509487~exp=1716513087~hmac=fe91bb21521f45bde049b7ce600fb2cc97d6eb557bb37c70c7a6dac2b5da81c1&w=1060",
                            Kcal = 2000,
                            Price = 35.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryDietId = 4,
                            Description = "Dieta dla aktywnych wegetarian, z dużą ilością nabiału, jaj, roślin strączkowych i pełnoziarnistych produktów, dostarczająca odpowiednią ilość białka i kalorii.",
                            DietName = "Veggie Boost 2500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/swieza-salatka-warzywna-z-bliska-na-kuchennym-stole_169016-49881.jpg?t=st=1716509498~exp=1716513098~hmac=e9137d9138b219b17fe3b3b73163a83cb8e43c8ed43e280aae49abb4ac2cfff2&w=1060",
                            Kcal = 2500,
                            Price = 35.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryDietId = 4,
                            Description = "Maksymalna energia dla wegetarian, z dużą ilością nabiału, jaj, warzyw, roślin strączkowych i pełnoziarnistych produktów, wspierająca aktywność i zdrowie.",
                            DietName = "Veggie Max 3000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/makaron-farfalle-z-pszenicy-durum-z-pieczonymi-klopsikami-fileta-z-kurczaka-w-sosie-pomidorowym-i-surowka-w-misce_2829-11169.jpg?t=st=1716509507~exp=1716513107~hmac=1d5943c3e8811bdb75d154fe35d97f84dea9d28d30ca9f40aafc430983e50797&w=1060",
                            Kcal = 3000,
                            Price = 35.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryDietId = 5,
                            Description = "Niskokaloryczna dieta oparta na mięsie, rybach i jajkach, minimalizująca spożycie innych składników, idealna dla osób redukujących wagę.",
                            DietName = "Carnivore Slim 1500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/widok-miesa-wolowego-na-tatar-ze-stekow_23-2150550508.jpg?t=st=1716509531~exp=1716513131~hmac=96ef7c54bf6fa3ff5756b16f583ab5135c18e0059046253a69fd1b00faee89ca&w=1060",
                            Kcal = 1500,
                            Price = 25.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryDietId = 5,
                            Description = "Zbilansowana dieta mięsna z większą ilością kalorii, zawierająca różnorodne rodzaje mięsa, ryby i jaja, dostarczająca energię i białko.",
                            DietName = "Carnivore Balance 2000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/prawdziwy-uklad-piramidy-zywieniowej-martwa-natura_23-2150238925.jpg?t=st=1716509546~exp=1716513146~hmac=cb5d237ad4fbbccd06b4ee4e8e2b07fa57727f06caf5df0a3b549e731283b430&w=1060",
                            Kcal = 2000,
                            Price = 25.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryDietId = 5,
                            Description = "Dieta dla aktywnych osób, bazująca na mięsie, rybach, jajach i tłustych produktach zwierzęcych, dostarczająca odpowiednią ilość białka i tłuszczów.",
                            DietName = "Carnivore Power 2500",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/widok-z-gory-pyszne-jedzenie-na-stole_23-2150227827.jpg?t=st=1716509558~exp=1716513158~hmac=61a49f28faee658adca93e779be8513cfa3b006cb308c146540d4a2bc90cf215&w=1060",
                            Kcal = 2500,
                            Price = 25.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryDietId = 5,
                            Description = "Maksymalna energia z mięsa dla osób o wysokim zapotrzebowaniu kalorycznym, z dużą ilością tłustych mięs, ryb, jaj i tłuszczów zwierzęcych, wspierająca intensywną aktywność fizyczną.",
                            DietName = "Carnivore Max 3000",
                            ImageUrl = "https://img.freepik.com/darmowe-zdjecie/zdrowy-obiad-obiad-w-misce-z-grillowanym-stekiem-wolowym-i-komosa-ryzowa-kukurydza-ogorkiem-rzodkiewka-i-rukola-na-drewnianym-stole-salatka-miesna_2829-6994.jpg?t=st=1716509573~exp=1716513173~hmac=ccc690fa8b3a6cde36cf635c1cc50d68ba10bf3c7ecff3fad428cf680f0b40dc&w=996",
                            Kcal = 3000,
                            Price = 25.0
                        });
                });

            modelBuilder.Entity("Fitness.Models.DietsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietsCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Dieta Ketogeniczna",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Dieta Wysokobiałkowa",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Dieta Wegańska",
                            DisplayOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Dieta Wegetariańska",
                            DisplayOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Dieta Karniworska",
                            DisplayOrder = 5
                        });
                });

            modelBuilder.Entity("Fitness.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Fitness.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetAddres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Fitness.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("Fitness.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DietId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Fitness.Models.Diet", b =>
                {
                    b.HasOne("Fitness.Models.DietsCategory", "DietsCategory")
                        .WithMany()
                        .HasForeignKey("CategoryDietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietsCategory");
                });

            modelBuilder.Entity("Fitness.Models.OrderDetail", b =>
                {
                    b.HasOne("Fitness.Models.Diet", "Diet")
                        .WithMany()
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("Fitness.Models.OrderHeader", b =>
                {
                    b.HasOne("Fitness.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Fitness.Models.ShoppingCart", b =>
                {
                    b.HasOne("Fitness.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness.Models.Diet", "Diet")
                        .WithMany()
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
